---
title: "Code for Figures"
author: "Mikaela Meyer"
date: "3/1/2022"
output: html_document
---

```{r,echo=FALSE, include = FALSE}
library(msm)
library(dplyr)
library(readxl)
library(knitr)
library(miceadds)
library(aods3)
library(car)
library(tidyverse)
library(ggplot2)
library(grid)
library(magrittr)
library(gridExtra)
library(MASS)
library(modelr)
library(ggrepel)
```

```{r, echo = FALSE}
# all crime: 2018-2020
crime_1820 <- read_excel("crime_3yrs.xlsx")
# remove first and last week of the year since they do not
# fall into any month by our categorization
crime_1820_df <- crime_1820[!(crime_1820$Week_Group == "0"),]
crime_1820_df$Year <- as.factor(crime_1820_df$Year)

# Remove weeks greater than week 38 for 2020
# crime_1820_df <- crime_1820_df %>% filter(Week <= 38 | Year != "2020")

# Create new response variables
crime_1820_df$Homicide_avg_byPop <- (crime_1820_df$Homicide_avg*52*100000)/crime_1820_df$Population
crime_1820_df$Homicide_diff_byPop <- (100000*crime_1820_df$Homicide*52)/crime_1820_df$Population - crime_1820_df$Homicide_avg_byPop

crime_1820_df$Robbery_avg_byPop <- (crime_1820_df$Robbery_avg*52*100000)/crime_1820_df$Population
crime_1820_df$Robbery_diff_byPop <- (100000*crime_1820_df$Robbery*52)/crime_1820_df$Population - crime_1820_df$Robbery_avg_byPop

crime_1820_df$Burglary_avg_byPop <- (crime_1820_df$`Burglary All_avg`*52*100000)/crime_1820_df$Population
crime_1820_df$Burglary_diff_byPop <- (100000*crime_1820_df$`Burglary All`*52)/crime_1820_df$Population - crime_1820_df$Burglary_avg_byPop

crime_1820_df$Auto_avg_byPop <- (crime_1820_df$`Auto Theft_avg`*52*100000)/crime_1820_df$Population
crime_1820_df$Auto_diff_byPop <- (100000*crime_1820_df$`Auto Theft`*52)/crime_1820_df$Population - crime_1820_df$Auto_avg_byPop

crime_1820_df$Larceny_avg_byPop <- (crime_1820_df$Larceny_avg*52*100000)/crime_1820_df$Population
crime_1820_df$Larceny_diff_byPop <- (100000*crime_1820_df$Larceny*52)/crime_1820_df$Population - crime_1820_df$Larceny_avg_byPop

# Filter out cities that aren't in top 70
crime_1820_df <- crime_1820_df %>% 
  filter(!City %in% c("Baton Rouge", "Chattanooga",
                      "Gainesville", "Hartford",
                      "Tacoma", "Tempe", "Lincoln")) # Lincoln removed due to lack of late 2020 data

# Remove first 11 weeks of 2019 for Kansas City due to the
# data being unavailable
crime_1820_df <- crime_1820_df %>% filter(!(City == "Kansas City" & Week %in% 1:11 & Year == "2019"))

# Clean Closeness index to make openness index
crime_1820_df <- mutate(crime_1820_df, 
                        Openness_Index =
                          abs(Closeness_Index - 14))
```

```{r, echo = FALSE}
# Create new variable: 2020 flag to be used in interactions for month model
crime_1820_df$Year_2020 <- ifelse(crime_1820_df$Year == "2020", 1, 0)
crime_1820_df$Year_2019 <- ifelse(crime_1820_df$Year == "2019", 1, 0)
crime_1820_df <- crime_1820_df %>% mutate("PrePandemic" = 
                                            ifelse(Year == 2020 & Month %in% c(1, 2), 1, 0),
                                          "Lockdown" = ifelse(Year == 2020 & Month %in% c(3,4,5), 1, 0),
                                          "Protests" = ifelse(Year == 2020 & Month %in% c(6,7,8), 1, 0),
                                          "End" = ifelse(Year ==2020 & Month %in% c(9:12), 1, 0))
crime_1820_df$Month <- as.factor(crime_1820_df$Month) #Otherwise, the first month isn't absorbed
# Create columns for per capita crime rates to use in city fixed effects models
crime_1820_df %<>%  
  mutate(Larceny_per_cap = (Larceny*100000*52)/Population,
         Burglary_per_cap = (`Burglary All`*100000*52)/Population,
         Robbery_per_cap = (Robbery*100000*52)/Population,
         Homicide_per_cap = (Homicide*100000*52)/Population,
         Auto_per_cap = (`Auto Theft`*100000*52)/Population)

#create data frame for openness index and biweekly lockdown models; stops at week 21
crime_openness <- crime_1820_df %>% filter(Week < min(Week[Surge_Protest_Week == 1]) | Year != "2020") %>% filter(City != "Milwaukee")

#create data frame for openness index; these cities do
#not have openness index data available
crime_openness_idx <- crime_openness %>% filter(!City %in% c("Tulsa", "Mesa",
                                                         "Raleigh", "Milwaukee",
                                                         "Saint Paul"))

hom_1820_df <- crime_1820_df %>% filter(City != "San Francisco") 
hom_openness <- crime_1820_df %>% filter(Week < min(Week[Surge_Protest_Week == 1]) | Year != "2020") %>% filter(!City %in% c("Milwaukee", "San Francisco"))

#create data frame for openness index; these cities do
#not have openness index data available
hom_oi <- crime_openness %>% filter(!City %in% c("Tulsa", "Mesa",
                                                         "Raleigh", "Milwaukee",
                                                         "Saint Paul", 
                                                         "San Francisco"))
```

# Openness Index Plots (Figure 1 and Appendix A.6)

```{r,echo=FALSE}
### Other plot based on email from 3/21
# Find first week when cities opened
crime_1820_df %>% dplyr::select(City, Year, Week, Weeks_from_lockdown, Openness_Index) %>% filter(Year == 2020 & Weeks_from_lockdown > 0 & Week <= 21) %>% mutate(Open_Week = as.numeric(Openness_Index > 0)) %>% group_by(City) %>% filter(Open_Week == 1) %>% slice(1)
# Find variation in openness index values
crime_1820_df %>% dplyr::select(City, Year, Week, Weeks_from_lockdown, Openness_Index) %>% filter(Year == 2020 & Weeks_from_lockdown > 0 & Week <= 21) %>% mutate(OIChangeFlag = as.numeric(Openness_Index - lag(Openness_Index) != 0)) %>% group_by(City) %>% summarize(OIChanges = sum(OIChangeFlag)) %>% filter(OIChanges == max(OIChanges, na.rm=T))
crime_1820_df %>% dplyr::select(City, Year, Week, Weeks_from_lockdown, Openness_Index) %>% filter(Year == 2020 & Weeks_from_lockdown > 0 & Week <= 21) %>% mutate(OIChangeFlag = as.numeric(Openness_Index - lag(Openness_Index) != 0)) %>% filter(City %in% c("Dallas", "Houston", "Nashville"))
# Find a place that never opened before week 21
crime_1820_df %>% dplyr::select(City, Year, Week, Weeks_from_lockdown, Openness_Index) %>% filter(Year == 2020 & Weeks_from_lockdown > 0 & Week == 21 & Openness_Index == 0)

selected_cities <- c("Atlanta", "Los Angeles", "Kansas City", "Boston", "Dallas", "Chicago")
crime_openness_idx %>% filter(Year == 2020 & Week >= 10 & Week <= 21) %>%
  dplyr::select(City, Week, Weeks_from_lockdown, Openness_Index) %>%
  mutate(label = ifelse(Weeks_from_lockdown == max(Weeks_from_lockdown),
                        City, NA_character_)) %>% 
  ggplot(aes(x = Week, y = Openness_Index, color = City)) + 
  geom_line(data = . %>% filter(!City %in% selected_cities), aes(x = Week, y = Openness_Index,
                                                                 group = City),
            colour = "grey") + geom_line(data = . %>% filter(City %in% selected_cities)) + 
  scale_x_continuous(breaks = 10:21) + labs(x = "Week of 2020",
                                                          y = "Openness Index") + scale_y_continuous(breaks = 0:14)

### Appendix Figure A.6
crime_openness_idx %>%
  filter(Year == 2020 & Week >= 10 & Week <= 21) %>%
  dplyr::select(City, Week, Weeks_from_lockdown, Openness_Index) %>%
  mutate(label = ifelse(Week == max(Week),
                        City, NA_character_),
         Region = factor(ifelse(City %in% c("Atlanta", "Louisville", "New York", "Pittsburgh"),
                                "Group 1", 
                                ifelse(City %in% c("Austin", "Los Angeles", "Denver", "San Francisco"), "Group 2",
                                       ifelse(City %in% c("Phoenix", "Kansas City", "Detroit", "Seattle"), "Group 3",
                                              ifelse(City %in% c("Houston", "Baltimore", "Chicago"),
                                                     "Group 4",
                                                     ifelse(City %in% c("Dallas", "Sacramento", "Nashville", "Washington"), "Group 5",
                                                            "Group 6"))))))) %>% #Other = St. Louis, Boston, Philadelphia, Cincinnati
  ggplot(aes(x = Week, y = Openness_Index, color = City)) + geom_line(data = . %>% dplyr::select(-Region), aes(x = Week, y = Openness_Index, group = City), colour = "grey") + geom_line() +  labs(x = "Week", y = "Openness Index", title = "Variation in Openness Index during Lockdown") + scale_y_continuous(breaks = seq(0, 14, by = 1)) + facet_wrap(~Region) + theme(legend.position = "none") + geom_label_repel(aes(label = label), nudge_x = 1, na.rm = TRUE) + scale_x_continuous(breaks = 10:21)
  
```

# Robbery Openness Index Plot (Figure 2)

```{r,echo=FALSE}
rob_openness_pois <- glm.cluster(data=crime_openness_idx, Robbery ~ Year + Month + Openness_Index + City + offset(log(Population)), cluster = 'City',
                                 family = "poisson")
summary(rob_openness_pois)

rop_no_cluster <- glm(data=crime_openness_idx, Robbery ~ Year + Month + Openness_Index + offset(log(Population)), family = "quasipoisson")
summary(rop_no_cluster)
```

```{r,echo=FALSE}
rob_oi_plot <- crime_openness_idx %>% filter(Year == 2020) %>% group_by(Week) %>% summarize(AvgOI = mean(Openness_Index)) %>% filter(Week >= 10)
rob_oi_plot <- rob_oi_plot %>% mutate(OIEffect = exp(coef(rob_openness_pois)[15]*AvgOI))
rob_oi_plot <- rob_oi_plot %>% mutate(AxisName = paste0(Week,
                                                        "\n(",
                                                        round(AvgOI, digits = 3), ")"))
rob_oi_plt <- ggplot(rob_oi_plot, aes(x = Week, y = OIEffect)) + geom_point(color = "purple") + geom_line(color = "purple") +
  labs(x = "Week and Average Openness Index Value", y = "Mult. Increase from Openness Index") + scale_x_continuous(breaks = 10:21, labels = rob_oi_plot$AxisName) + theme(axis.text.x = element_text(angle = 90))

rob_oi_plt
```

# Figure 3: Robbery Biweek

```{r,echo=FALSE}
rob_biweek_pois <- glm.cluster(data = crime_openness, `Robbery` ~ Year +
                                 Month + `LD_-1/0` + `LD_1/2` + `LD_3/4` +
                                 `LD_5/6` + `LD_7/8` + `LD_9/10` + City +
                                 offset(log(Population)),
                              cluster = 'City', family = "poisson")

coef_biweek <- coef(rob_biweek_pois)[15:20]
rob_open_std_errors <- deltamethod(list(~ exp(x1), ~exp(x2), ~exp(x3), ~exp(x4), ~exp(x5),
                                        ~exp(x6)), coef_biweek,
                                    vcov(rob_biweek_pois)[15:20, 15:20])
rob_open_graph_df <- data.frame("BiweekVar" = c("-1/0", "1/2",
                                                "3/4", "5/6",
                                                "7/8", "9/10"),
                                "Coef" = exp(coef_biweek),
                                "Upper" = exp(coef_biweek) +
                                  (1.96*rob_open_std_errors),
                                "Lower" = exp(coef_biweek) -
                                  (1.96*rob_open_std_errors))

fig3 <- ggplot(rob_open_graph_df, aes(x = BiweekVar, y = Coef)) +
  geom_point(color = "dark green") + geom_errorbar(aes(ymin = Lower,
                                             ymax = Upper), color = "dark green") +
  labs(x = "Weeks since Lockdown", y = "Lockdown Impact on Robbery") + #make sure you change crime type in yaxis label
  geom_hline(yintercept = 1, linetype = "dashed")+ #same comment as previous plot; might need to set ylim
  ylim(0.5,1.5)
fig3
```

# Figure 4: Larceny Biweek

```{r,echo=FALSE}
lar_biweek_pois <- glm.cluster(data = crime_openness, `Larceny` ~ Year +
                                 Month + `LD_-1/0` + `LD_1/2` + `LD_3/4` +
                                 `LD_5/6` + `LD_7/8` + `LD_9/10` + City +
                                 offset(log(Population)),
                              cluster = 'City', family = "poisson")

coef_biweek <- coef(lar_biweek_pois)[15:20]
lar_open_std_errors <- deltamethod(list(~ exp(x1), ~exp(x2), ~exp(x3), ~exp(x4), ~exp(x5), 
                                        ~exp(x6)), coef_biweek,
                                    vcov(lar_biweek_pois)[15:20, 15:20])
lar_open_graph_df <- data.frame("BiweekVar" = c("-1/0", "1/2",
                                                "3/4", "5/6",
                                                "7/8", "9/10"),
                                "Coef" = exp(coef_biweek),
                                "Upper" = exp(coef_biweek) +
                                  (1.96*lar_open_std_errors),
                                "Lower" = exp(coef_biweek) -
                                  (1.96*lar_open_std_errors))

fig4 <- ggplot(lar_open_graph_df, aes(x = BiweekVar, y = Coef)) +
  geom_point(color = "dark green") + geom_errorbar(aes(ymin = Lower,
                                             ymax = Upper), color = "dark green") +
  labs(x = "Weeks since Lockdown", y = "Lockdown Impact on Larceny") + #make sure you change crime type in yaxis label
  geom_hline(yintercept = 1, linetype = "dashed")+ #same comment as previous plot; might need to set ylim
  ylim(0.5,1.5)
fig4
```

# Figure 5: Homicide Biweek

```{r,echo=FALSE}
hom_biweek_pois <- glm.cluster(data = hom_openness, Homicide ~ Year +
                                 Month + `LD_-1/0` + `LD_1/2` + `LD_3/4` +
                                 `LD_5/6` + `LD_7/8` + `LD_9/10` + City +
                                 offset(log(Population)),
                              cluster = 'City', family = "poisson")
summary(hom_biweek_pois)

coef_biweek <- coef(hom_biweek_pois)[15:20]
print(coef_biweek)
hom_open_std_errors <- deltamethod(list(~ exp(x1), ~exp(x2), ~exp(x3), ~exp(x4), ~exp(x5), ~exp(x6)),
                                   coef_biweek,
                                    vcov(hom_biweek_pois)[15:20, 15:20])
hom_open_std_errors
hom_open_graph_df <- data.frame("BiweekVar" = c("-1/0", "1/2",
                                                "3/4", "5/6",
                                                "7/8", "9/10"),
                                "Coef" = exp(coef_biweek),
                                "Upper" = exp(coef_biweek) +
                                  (1.96*hom_open_std_errors),
                                "Lower" = exp(coef_biweek) -
                                  (1.96*hom_open_std_errors))
print(hom_open_graph_df)

fig5 <- ggplot(hom_open_graph_df, aes(x = BiweekVar, y = Coef)) +
  geom_point(color = "dark green") + geom_errorbar(aes(ymin = Lower,
                                             ymax = Upper), color = "dark green") +
  labs(x = "Weeks since Lockdown", y = "Lockdown Impact on Homicide") + #make sure you change crime type in yaxis label
  geom_hline(yintercept = 1, linetype = "dashed")+ #same comment as previous plot; might need to set  
  ylim(0.5, 1.5)
fig5
```

# Figure 6: Auto Theft Biweek

```{r,echo=FALSE}
auto_biweek_pois <- glm.cluster(data = crime_openness, `Auto Theft` ~ Year +
                                 Month + `LD_-1/0` + `LD_1/2` + `LD_3/4` +
                                 `LD_5/6` + `LD_7/8` + `LD_9/10` + City +
                                 offset(log(Population)),
                              cluster = 'City', family = "poisson")

coef_biweek <- coef(auto_biweek_pois)[15:20]
auto_open_std_errors <- deltamethod(list(~ exp(x1), ~exp(x2), ~exp(x3), ~exp(x4), ~exp(x5),
                                         ~exp(x6)), coef_biweek,
                                    vcov(auto_biweek_pois)[15:20, 15:20])
auto_open_graph_df <- data.frame("BiweekVar" = c("-1/0", "1/2",
                                                "3/4", "5/6",
                                                "7/8", "9/10"),
                                "Coef" = exp(coef_biweek),
                                "Upper" = exp(coef_biweek) +
                                  (1.96*auto_open_std_errors),
                                "Lower" = exp(coef_biweek) -
                                  (1.96*auto_open_std_errors))

fig6 <- ggplot(auto_open_graph_df, aes(x = BiweekVar, y = Coef)) +
  geom_point(color = "dark green") + geom_errorbar(aes(ymin = Lower,
                                             ymax = Upper), color = "dark green") +
  labs(x = "Weeks since Lockdown", y = "Lockdown Impact on Auto Theft") + #make sure you change crime type in yaxis label
  geom_hline(yintercept = 1, linetype = "dashed")+ #same comment as previous plot; might need to set  ylim
  ylim(0.5,1.5)
fig6
```

# Figure 7: Burglary Biweek

```{r,echo=FALSE}
burg_biweek_pois <- glm.cluster(data = crime_openness, `Burglary All` ~ Year +
                                 Month + `LD_-1/0` + `LD_1/2` + `LD_3/4` +
                                 `LD_5/6` + `LD_7/8` + `LD_9/10` + City +
                                 offset(log(Population)),
                              cluster = 'City', family = "poisson")

coef_biweek <- coef(burg_biweek_pois)[15:20]
burg_open_std_errors <- deltamethod(list(~ exp(x1), ~exp(x2), ~exp(x3), ~exp(x4), ~exp(x5),
                                         ~exp(x6)), coef_biweek,
                                    vcov(burg_biweek_pois)[15:20, 15:20])
burg_open_graph_df <- data.frame("BiweekVar" = c("-1/0", "1/2",
                                                "3/4", "5/6",
                                                "7/8", "9/10"),
                                "Coef" = exp(coef_biweek),
                                "Upper" = exp(coef_biweek) +
                                  (1.96*burg_open_std_errors),
                                "Lower" = exp(coef_biweek) -
                                  (1.96*burg_open_std_errors))

fig7 <- ggplot(burg_open_graph_df, aes(x = BiweekVar, y = Coef)) +
  geom_point(color = "dark green") + geom_errorbar(aes(ymin = Lower,
                                             ymax = Upper), color = "dark green") +
  labs(x = "Weeks since Lockdown", y = "Lockdown Impact on Burglary") + #make sure you change crime type in yaxis label
  geom_hline(yintercept = 1, linetype = "dashed")+ #same comment as previous plot; might need to set ylim
  ylim(0.5,2)
fig7
```

# Figure 8: Homicide Seasonal

```{r,echo=FALSE}
hom_seasonal_pois <- glm.cluster(Homicide ~ Year_2019 + Month + PrePandemic +
                           Lockdown + Protests + End + City +
                           offset(log(Population)), data = hom_1820_df,
                           cluster = "City", family = "poisson")

new_seasonal_plt <- function(mylm){
  coef_2020 <- coef(mylm)[14:17] #these are coefficients for PrePandemic, Lockdown, Protests, and End of 2020
  std_errors <- deltamethod(list(~ exp(x1), ~exp(x2), ~exp(x3), ~exp(x4)), coef_2020,
                                    vcov(mylm)[14:17, 14:17])

  graph_df <- data.frame("Partsof2020" = names(coef_2020),
                       "Coefficients" = exp(coef_2020),
                       "UpperBd" = exp(coef_2020) + (1.96*std_errors),
                       "LowerBd" = exp(coef_2020) - (1.96*std_errors))

  graph_df <- graph_df %>% mutate(Partsof2020 = fct_relevel(Partsof2020,
                                                          "PrePandemic",
                                                          "Lockdown",
                                                          "Protests",
                                                          "End"))

  new_plt <- ggplot(graph_df, aes(x = Partsof2020, y = Coefficients)) +
  geom_point(color = "blue") + geom_errorbar(mapping = aes(ymax = UpperBd,
                                                           ymin = LowerBd),
                                             color = "blue") +
  geom_hline(yintercept = 1, linetype = "dashed") 
  return(new_plt)
}

fig8 <- new_seasonal_plt(hom_seasonal_pois) + 
  labs(x = "Periods of 2020", y = "Change in Homicide Rates") +
  scale_x_discrete(labels = c(
    "PrePandemic" = "Pre-Pandemic", "Protests" = "Summer Protests",
    "End" = "End of the Year")) + ylim(0, 2) 

fig8
```

# Figure 9: Auto Theft Seasonal

```{r,echo=FALSE}
auto_seasonal_pois <- glm.cluster(`Auto Theft` ~ Year_2019 + Month + PrePandemic +
                           Lockdown + Protests + End + City +
                           offset(log(Population)), data = crime_1820_df,
                           cluster = "City", family = "poisson")
summary(auto_seasonal_pois)

fig9 <- new_seasonal_plt(auto_seasonal_pois) + 
  labs(x = "Periods of 2020", y = "Change in Auto Theft Rates") +
  scale_x_discrete(labels = c(
    "PrePandemic" = "Pre-Pandemic", "Protests" = "Summer Protests",
    "End" = "End of the Year")) + ylim(0, 2) 

fig9
```

# Figure 10: Burglary Seasonal

```{r,echo=FALSE}
burg_seasonal_pois <- glm.cluster(`Burglary All` ~ Year_2019 + Month + PrePandemic +
                           Lockdown + Protests + End + City +
                           offset(log(Population)), data = crime_1820_df,
                           cluster = "City", family = "poisson")
summary(burg_seasonal_pois)

fig10 <- new_seasonal_plt(burg_seasonal_pois) + 
  labs(x = "Periods of 2020", y = "Change in Burglary Rates") +
  scale_x_discrete(labels = c(
    "PrePandemic" = "Pre-Pandemic", "Protests" = "Summer Protests",
    "End" = "End of the Year")) + ylim(0.5, 1.5) 

fig10
```

# Figure 11: Robbery Seasonal

```{r,echo=FALSE}
rob_seasonal_pois <- glm.cluster(`Robbery` ~ Year_2019 + Month + PrePandemic +
                           Lockdown + Protests + End + City +
                           offset(log(Population)), data = crime_1820_df,
                           cluster = "City", family = "poisson")
summary(rob_seasonal_pois)

fig11 <- new_seasonal_plt(rob_seasonal_pois) + 
  labs(x = "Periods of 2020", y = "Change in Robbery Rates") +
  scale_x_discrete(labels = c(
    "PrePandemic" = "Pre-Pandemic", "Protests" = "Summer Protests",
    "End" = "End of the Year")) + ylim(0.5, 1.5) 

fig11
```

# Figure 12: Larceny Seasonal

```{r,echo=FALSE}
lar_seasonal_pois <- glm.cluster(`Larceny` ~ Year_2019 + Month + PrePandemic +
                           Lockdown + Protests + End + City +
                           offset(log(Population)), data = crime_1820_df,
                           cluster = "City", family = "poisson")
summary(lar_seasonal_pois)

fig12 <- new_seasonal_plt(lar_seasonal_pois) + 
  labs(x = "Periods of 2020", y = "Change in Larceny Rates") +
  scale_x_discrete(labels = c(
    "PrePandemic" = "Pre-Pandemic", "Protests" = "Summer Protests",
    "End" = "End of the Year")) + ylim(0.5, 1.5) 

fig12
```



